# Generated by Django 2.2.4 on 2019-08-20 16:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='First Account', max_length=135, verbose_name="Account's Full Name")),
                ('short_name', models.CharField(max_length=100, verbose_name='Account Short Name')),
                ('url', models.CharField(blank=True, max_length=165, verbose_name="Account's Website URL")),
                ('description', models.TextField(blank=True, max_length=765, null=True, verbose_name='Description/Notes')),
                ('link_to_description_relationship', models.CharField(blank=True, max_length=165, verbose_name='Link to Description of Relationship')),
                ('link_to_due_diligence', models.CharField(blank=True, max_length=165, verbose_name='Link to Due Diligence')),
                ('singular_label', models.CharField(blank=True, default='Account', max_length=135, verbose_name='Account Singular Label')),
                ('plural_label', models.CharField(blank=True, default='Accounts', max_length=135, verbose_name='Account Plural Label')),
                ('organization_identifier', models.CharField(blank=True, max_length=100, verbose_name='Account Identifier')),
                ('organization_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, verbose_name='Account Status')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 1')),
                ('level_2', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 2')),
                ('level_3', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 3')),
                ('level_4', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 4')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_account', to='circlescore.Account')),
            ],
            options={
                'verbose_name_plural': 'Administrative Levels',
                'ordering': ('level_1',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('singular_label', models.CharField(default='Contact', max_length=100, verbose_name='Singular Label')),
                ('plural_label', models.CharField(default='Contacts', max_length=100, verbose_name='Plural Label')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=25, verbose_name='Zip/Postal Code')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_account', to='circlescore.Account')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country Name')),
                ('code', models.CharField(blank=True, max_length=4, verbose_name='2 Letter Country Code')),
                ('description', models.TextField(blank=True, max_length=765, verbose_name='Description/Notes')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('zoom', models.IntegerField(default=5, verbose_name='Zoom')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='HikayaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], max_length=3, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('employee_number', models.IntegerField(blank=True, null=True, verbose_name='Employee Number')),
                ('privacy_disclaimer_accepted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hikaya_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Workspace UUID')),
                ('name', models.CharField(max_length=36, verbose_name='Workspace Name')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='Workspace Url')),
                ('description', models.TextField(blank=True, max_length=765, verbose_name='Workspace Description')),
                ('workflow_level_1', models.CharField(default='Project', max_length=36)),
                ('workflow_level_2', models.CharField(default='Activity', max_length=36)),
                ('workflow_level_3', models.CharField(default='Sub-Activity', max_length=36)),
                ('workflow_level_4', models.CharField(default='Task', max_length=36)),
                ('organization_label', models.CharField(default='Account', max_length=36)),
                ('indicator_label', models.CharField(default='Indicator', max_length=36)),
                ('form_label', models.CharField(default='Forms', max_length=36)),
                ('site_label', models.CharField(default='Sites', max_length=36)),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name_plural': 'Workspaces',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector Name')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_account', to='circlescore.Account')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_created_by', to='circlescore.HikayaUser', verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('parent_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sectors', to='circlescore.Sector')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Location',
                'ordering': ('sector',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Portfolio UUID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Portfolio Name')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_account', to='circlescore.Account')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_created_by', to='circlescore.HikayaUser', verbose_name='Created Vy')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Office Name')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Office Code')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_account', to='circlescore.Account')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_created_by', to='circlescore.HikayaUser', verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_workspace', to='circlescore.Workspace')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Workspace Sub-Type UUID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Location Type')),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_account', to='circlescore.Account')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_created_by', to='circlescore.HikayaUser', verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Location Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Location UUID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Site Name')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='Location Status')),
                ('latitude', models.DecimalField(decimal_places=16, default=Decimal('0.00'), max_digits=25, verbose_name='Latitude Coordinates')),
                ('longitude', models.DecimalField(decimal_places=16, default=Decimal('0.00'), max_digits=25, verbose_name='Longitude Coordinates')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_account', to='circlescore.Account')),
                ('admin_levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.AdministrativeLevel', verbose_name='Administrative Levels')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Contact', verbose_name='Location Contact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circlescore.Country', verbose_name='Country of Location')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to='circlescore.HikayaUser', verbose_name='Created by')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Office', verbose_name='Location Office')),
                ('parent_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='circlescore.Location')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.LocationType', verbose_name='Location Type')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='hikayauser',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_workspace', to='circlescore.Workspace'),
        ),
        migrations.AddField(
            model_name='hikayauser',
            name='workspaces',
            field=models.ManyToManyField(blank=True, related_name='user_workspaces', to='circlescore.Workspace', verbose_name='Accessible Workspaces'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135, null=True, verbose_name='Name of Document')),
                ('url', models.CharField(blank=True, max_length=135, null=True, verbose_name='URL (Link to document or document repository)')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Currency UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Currency Name')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Currency Symbol')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Currency Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_account', to='circlescore.Account')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_created_by', to='circlescore.HikayaUser', verbose_name='Created Vy')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='country',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Workspace'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created_by', to='circlescore.HikayaUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_workspace', to='circlescore.Workspace'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_created_by', to='circlescore.HikayaUser', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_workspace', to='circlescore.Workspace'),
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Account Type UUID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Account Type')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Edit Date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_type_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_type_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_type_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Account Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='AccountSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Account Sub-Type UUID')),
                ('sub_type', models.CharField(max_length=100, unique=True, verbose_name='Account Sub-Type')),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sub_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sub_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.AccountType', verbose_name='Account Type')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_Sub_type_workspace', to='circlescore.Workspace')),
            ],
            options={
                'verbose_name_plural': 'Account Sub Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='documentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Document'),
        ),
        migrations.AddField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='account',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='circlescore.Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_workspace', to='circlescore.Workspace'),
        ),
    ]
