# Generated by Django 2.2.4 on 2019-08-22 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Account UUID'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='admin_level_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Admin Level UUID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Contact UUID'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Country UUID'),
        ),
        migrations.AddField(
            model_name='hikayauser',
            name='hikaya_user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Hikaya User UUID'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Office UUID'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Sector UUID'),
        ),
    ]
