# Generated by Django 2.2.4 on 2019-08-24 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0002_auto_20190822_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Document UUID'),
        ),
    ]
