# Generated by Django 2.2.4 on 2019-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0003_document_document_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='workspace',
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
