# Generated by Django 2.2.4 on 2019-09-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0004_auto_20190907_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='account',
        ),
        migrations.RemoveField(
            model_name='location',
            name='admin_levels',
        ),
        migrations.AddField(
            model_name='location',
            name='admin_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.AdministrativeLevel', verbose_name='Administrative Levels'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Contact', verbose_name='Location Contact'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circlescore.Country', verbose_name='Country of Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to='circlescore.HikayaUser', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Office', verbose_name='Location Office'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='circlescore.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.LocationType', verbose_name='Location Type'),
        ),
    ]
