# Generated by Django 2.2.4 on 2019-09-26 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0006_auto_20190926_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_uuid',
            field=models.UUIDField(default=uuid.UUID('94d303ae-48f1-44b5-a279-691b3027b5fc'), editable=False, unique=True, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(default=uuid.UUID('5afe3611-2a8b-4688-bbdf-5ffccb61312d'), editable=False, unique=True, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalapproval',
            name='approval_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('94d303ae-48f1-44b5-a279-691b3027b5fc'), editable=False, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='historicalfundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5afe3611-2a8b-4688-bbdf-5ffccb61312d'), editable=False, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level 2/3 Description'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='workflow_level2_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow Level2 Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level 2/3 Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='implementation_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Location', verbose_name='Implementation Location Tag'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Office', verbose_name='Office Location Tag'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_level3s', to='circlescore.WorkflowLevel2'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='staff_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.Contact', verbose_name='Staff Responsible'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflow_level2_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow Level2 Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflow_level2_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.WorkflowLevel2Type', verbose_name='Workflow Level 2 Type'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflow_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.WorkflowStatus', verbose_name='Workflow Status'),
        ),
    ]
