# Generated by Django 2.2.4 on 2019-09-26 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0007_auto_20190926_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_uuid',
            field=models.UUIDField(default=uuid.UUID('eb6622fe-50ec-41b4-b236-6149943b6402'), editable=False, unique=True, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(default=uuid.UUID('7ce59d26-a5a2-406d-a83e-aae9c329b37a'), editable=False, unique=True, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalapproval',
            name='approval_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('eb6622fe-50ec-41b4-b236-6149943b6402'), editable=False, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='historicalfundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7ce59d26-a5a2-406d-a83e-aae9c329b37a'), editable=False, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel1',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level 1 Description'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel1',
            name='workflow_level1_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow Level 1 Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level 1 Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='workflow_level1_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow Level 1 Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='workflow_level1_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.WorkflowLevel1Type', verbose_name='Workflow Level 1 Type'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='workflow_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.WorkflowStatus', verbose_name='Workflow Status'),
        ),
    ]
