# Generated by Django 2.2.4 on 2019-09-26 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0008_auto_20190926_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_uuid',
            field=models.UUIDField(default=uuid.UUID('8c939a50-0684-497c-b591-f0465fab68bb'), editable=False, unique=True, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(default=uuid.UUID('cf4b4e70-ae6d-41a9-9fd1-6815f3c48cf1'), editable=False, unique=True, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalapproval',
            name='approval_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('8c939a50-0684-497c-b591-f0465fab68bb'), editable=False, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='historicalfundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('cf4b4e70-ae6d-41a9-9fd1-6815f3c48cf1'), editable=False, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='funding_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='circlescore.FundingStatus', verbose_name='Funding Status'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='sector',
            field=models.ManyToManyField(blank=True, help_text='Workflow Level 1 sectors', null=True, to='circlescore.Sector'),
        ),
    ]
