# Generated by Django 2.2.4 on 2019-09-26 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0009_auto_20190926_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_uuid',
            field=models.UUIDField(default=uuid.UUID('cf850fc6-138f-427e-ad30-c2105bd9c4af'), editable=False, unique=True, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(default=uuid.UUID('51078feb-e9e2-4e1f-aad7-33232cb69d70'), editable=False, unique=True, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalapproval',
            name='approval_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('cf850fc6-138f-427e-ad30-c2105bd9c4af'), editable=False, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='historicalfundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('51078feb-e9e2-4e1f-aad7-33232cb69d70'), editable=False, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wfl1_created_by', to='circlescore.HikayaUser', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wfl1_modified_by', to='circlescore.HikayaUser', verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='sector',
            field=models.ManyToManyField(blank=True, help_text='Workflow Level 1 sectors', to='circlescore.Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circlescore.Workspace'),
        ),
    ]
