# Generated by Django 2.2.4 on 2019-09-26 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0010_auto_20190926_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_uuid',
            field=models.UUIDField(default=uuid.UUID('18e44e6f-2164-4d11-af19-3dc37c1aefea'), editable=False, unique=True, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='fundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(default=uuid.UUID('9cd4c53e-4daf-4942-ad01-cc1aadf4fa32'), editable=False, unique=True, verbose_name='Funding Status UUID'),
        ),
        migrations.AlterField(
            model_name='historicalapproval',
            name='approval_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('18e44e6f-2164-4d11-af19-3dc37c1aefea'), editable=False, verbose_name='Approval UUID'),
        ),
        migrations.AlterField(
            model_name='historicalfundingstatus',
            name='funding_status_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9cd4c53e-4daf-4942-ad01-cc1aadf4fa32'), editable=False, verbose_name='Funding Status UUID'),
        ),
    ]
