# Generated by Django 2.2.4 on 2019-09-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0012_auto_20190926_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel1',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circlescore.Workspace'),
        ),
    ]
