# Generated by Django 2.2.4 on 2019-09-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0013_auto_20190926_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2plan',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level2 Plan Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2plan',
            name='description',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Workflow Level2 Plan Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2plan',
            name='workflow_level2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circlescore.WorkflowLevel2', verbose_name='Workflow Level 2'),
        ),
    ]
