# Generated by Django 2.2.4 on 2019-09-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circlescore', '0015_auto_20190927_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organization_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='organization_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='Account Status'),
        ),
    ]
